### ISSUE TITLE
How many machines do you use to generate 1M cache  training data? 

### ISSUE THREAD

**Issue by Zhaoguanhua** [jchengai/planTF#10]
I am following readme to generate training cache data from the whole nuplan training set，as you say,in the Feature cache stage：
![plantf](https://github.com/jchengai/planTF/assets/33119925/f4710991-24ea-41f2-b674-f6e2bf69c656)
it means it cost 20+ hours to generate 1M trainning data?。
how many machines do you use to generate 1M cache  training data? and each machine's information（how many cores，RAM...）?

**Comment by jchengai** [comment]
> it means it cost 20+ hours to generate 1M trainning data?

Yes, but the cache time is heavily affected by the I/O speed of the disk. Using a SSD can half the time.

> how many machines do you use to generate 1M cache training data? and each machine's information（how many cores，RAM...）?

A server with 48 cores and 180G RAM.

**Comment by Zhaoguanhua** [comment]
Thanks! in my case ,it will be cost 10+ days to generate 1M data,one machine（40 cores and 160G RAM）. i think I/O speed is the biggest problem for me。

**Comment by jessapinkman** [comment]
hi, @jchengai 

I encountered the same problem in processing cache data, and it took much longer than 20 hours(one machine（48 cores and 256G RAM）. In addition to increasing the number of threads, are there any other ways to improve efficiency? Will the number of ray nodes affect this?

**Comment by jchengai** [comment]
Hi @jessapinkman, which worker do you use? I used the ray distributed worker with 40 ray nodes in a docker container.

**Comment by jessapinkman** [comment]
> Hi @jessapinkman, which worker do you use? I used the ray distributed worker with 40 ray nodes in a docker container.

 I used the ray distributed worker with 20 ray nodes in a docker container. It needs much time for caching. Maybe it's because I'm reading and writing data on a Mechanical hard disk, but my SSD memory isn't big enough to move the entire data set to the SSD.
![image](https://github.com/jchengai/planTF/assets/96737842/3c1b0cc3-8521-49b5-9844-37f60f819330)
