### ISSUE TITLE
problem about evaluation

### ISSUE THREAD

**Issue by jessapinkman** [jchengai/planTF#19]
hi, @jchengai 
here is my config when I evaluate the trained model:
`cwd=$(pwd)
CKPT_ROOT="$cwd/checkpoints"
PLANNER="planTF"
SPLIT=$1
CHALLENGES="closed_loop_nonreactive_agents closed_loop_reactive_agents open_loop_boxes"

for challenge in $CHALLENGES; do
    python run_simulation.py \
        +simulation=$challenge \
        planner=$PLANNER \
        scenario_builder=nuplan_challenge \
        scenario_filter=$SPLIT \
        worker.threads_per_node=10 \
        worker=ray_distributed \
        # worker=sequential \
        # worker.use_distributed=true \
        experiment_uid=$SPLIT/$planner \
        verbose=true \
        planner.imitation_planner.planner_ckpt="$CKPT_ROOT/$PLANNER.ckpt"
done`

Number of nodes: 1
Number of CPUs per node: 10
Number of GPUs per node: 3
Number of threads across all nodes: 10 This is the setting I ran the program with, but the number of threads kept increasing, eventually causing two simulation failures:
1.RAM is full
2. The GPU memory is full
Both of the above situations will cause simulation failure and program blocking. The number of processes running the simulation keeps increasing; even when I set export RAY_memory_usage_threshold=0.6 to limit RAM memory usage, this does not work, which causes the simulation to fail. How can I solve the above problem?

**Comment by jessapinkman** [comment]
@jchengai Much appreciation if you could help me.

**Comment by jchengai** [comment]
1. I used to run the benchmark on a server (in a docker container) with 200+G RAM and I have not encountered any problems. If you only have small RAM, maybe you should try the sequential worker or decrease the number of threads. 

2. You can change the self.device to cpu and it has little impact on the simulation speed. 
https://github.com/jchengai/planTF/blob/86e3b718c0bb1dd750bb22fadcc93e6113669c4c/src/planners/imitation_planner.py#L76-L77

**Comment by jessapinkman** [comment]
yes, actually I run the benchmark on a server (also in a docker container) with 256G RAM and 8 A100, but the memory(both GPU and CPU) always increases without limitation when I use ray_distributed for simulation and the following problem appears:

(raylet) [2024-05-13 16:17:22,715 E 2713522 2713522] (raylet) node_manager.cc:3024: 3 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: 4829cd4f17bd5ab0aa89c49741fdec4017255778bf9c10b8675fdb31, IP: 172.17.0.18) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.17.0.18`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

Also, I have already used the sequential worker to isolate this problem. But it takes too much time for each simulation(more the one minute for 15 sec. simulation)

**Comment by fty2000** [comment]
hello,have you solved the problem? @jessapinkman

**Comment by jessapinkman** [comment]
> hello,have you solved the problem? @jessapinkman

yes, you can set sequential worker to isolate this problem. Hope it help u :)
