### ISSUE TITLE
The training process got stuck.

### ISSUE THREAD

**Issue by wangck20** [jchengai/planTF#2]
Hi, thanks for this constructive job!
I followed the training command as bellow shown below after I preprocess the dataset.
![image](https://github.com/jchengai/planTF/assets/81554906/84b89979-3c47-4859-acf4-5385dc48d530)
However, I found that the number of gpus per node was 0, shown below.
![image](https://github.com/jchengai/planTF/assets/81554906/8c7e70c3-1618-47aa-861f-c22b81a9fa71)
Besides, the training process got stuck as below.
![image](https://github.com/jchengai/planTF/assets/81554906/32ab162e-2928-4843-b091-c7e49182967f)
I wonder if there is something wrong with the setting and thanks in advance for any help!

**Comment by jchengai** [comment]
Hi, @wangck20,

> However, I found that the number of gpus per node was 0, shown below.

I have the same printings, but does not affect the training.

> Besides, the training process got stuck as below.

It may take some while to load the data, depends on your hardware. Besides, you may try to use a smaller data split for a quick sanity check. e.g., 

```
CUDA_VISIBLE_DEVICES=0 python run_training.py \      
  py_func=train +training=train_planTF \
  worker=single_machine_thread_pool worker.max_workers=32 \
  data_loader.params.batch_size=4 data_loader.params.num_workers=4 \
  lr=1e-3 epochs=25 warmup_epochs=3 weight_decay=0.0001 scenario_filter=mini data_loader.params.batch_size=4
```

**Comment by Jiale-Fan** [comment]
I had the same issue. It is basically because when reading cache, nuPlan would iterate through the directories of all .gz files, whose number is up to 2 million and it would take a long time, and this is not sign of getting stuck. It takes about 1 hour on my workstation with HDD, and I suspect it would take less time if your computer is equipped with SSD. 

To see the progress bar during this procedure, you can search for the get_local_scenario_cache function in nuplan-devkit and modify it as follows. 

`def get_local_scenario_cache(cache_path: str, feature_names: Set[str]) -> List[Path]:
    """
    Get a list of cached scenario paths from a local cache.
    :param cache_path: Root path of the local cache dir.
    :param feature_names: Set of required feature names to check when loading scenario paths from the cache.
    :return: List of discovered cached scenario paths.
    """
    cache_dir = Path(cache_path)
    assert cache_dir.exists(), f'Local cache {cache_dir} does not exist!'
    assert any(cache_dir.iterdir()), f'No files found in the local cache {cache_dir}!'

    # candidate_scenario_dirs = {x.parent for x in cache_dir.rglob("*.gz")}
    candidate_scenario_dirs = set()
    for x in tqdm(cache_dir.rglob("*.gz"), desc="Finding scenario directories"):
        candidate_scenario_dirs.add(x.parent)

    # Keep only dir paths that contains all required feature names
    scenario_cache_paths = [
        path
        for path in candidate_scenario_dirs
        if not (feature_names - {feature_name.stem for feature_name in path.iterdir()})
    ]

    return scenario_cache_paths`

**Comment by jchengai** [comment]
Thanks for your explanation. In my case, it took about 1 minute to read the caches with a SATA SSD.
