### ISSUE TITLE
Visualization Issues

### ISSUE THREAD

**Issue by dswangabel** [jchengai/planTF#4]
Hi, thank you for sharing the great work!

       Can you share the visualization script based on Nuboard？

Bests.

**Comment by jchengai** [comment]
Hi @dswangabel, the visualization was directly exported from Nuboard. Could you specify which part you're referring to?

**Comment by dswangabel** [comment]
Thank for you reply!  
I want to evaluate the results using the checkpoints you provided . when i run sh ./script/plantf_single_scenarios.sh  in the terminal,  there are no Nuboard results presented.   I konw the visualization was directly exported from Nuboard, but  the scrtpt run_simulation.py looks not uses Nuboard, how can you do or what script you run?
Bests.

**Comment by jchengai** [comment]
The nuboard script (copy from nuplan-devkit) is added for convenience with the latest commit. Just run `python run_nuboard.py` and upload the experiment logging file (xxx.nuboard).

**Comment by dswangabel** [comment]
You're very welcome! . Good luck with you!
