### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by dswangabel** [jchengai/planTF#5]
Hi,
I run the example of  training script in the terminal, and the process is smoothly. Then i want training the model based on your provided  checkpoints, and i configured the checkpoint path in the  "default_training.yaml", but it's causing an error. Do you know the reason?
Bests.
![1](https://github.com/jchengai/planTF/assets/123939640/a24d2c09-39b2-45ba-9f07-553287cd046e)
![2](https://github.com/jchengai/planTF/assets/123939640/e95fb3d2-7b34-44da-8ff1-f9858cfeb708)

**Comment by jchengai** [comment]
Hi, @dswangabel, the provided checkpoints only contain the trained model weights and the optimizer state is not included. BTW, why would you like to re-train the model with the trained checkpoint.
