### ISSUE TITLE
Question about the output of the model (future steps)

### ISSUE THREAD

**Issue by weiaiF** [jchengai/planTF#7]
Hi, I want to change the model's output parameter **future steps** from 80 to 16. However,the prompt indicates that the ego vehicle and the expert have different trajectory lengths.
![F60JHR7(L{A55U1BG6%IL5O](https://github.com/jchengai/planTF/assets/72204912/f637a26a-0fc3-41cb-8eb7-2a335070df03)

**Comment by weiaiF** [comment]
The issue has been resolved.

**Comment by dswangabel** [comment]
Hi, if i change the model's output parameter future steps from 80 to 30 or other number ,  will the model's outcome be affected?
