### ISSUE TITLE
About the test14 split

### ISSUE THREAD

**Issue by ynw2021** [jchengai/planTF#8]
Hi, great work!
When I check your test14-random and test14_hard splits, it seems that the samples are extracted from the whole dataset: both from the train set and the val set. Is that true?

**Comment by jchengai** [comment]
Hi @ynw2021, thanks for your interest in our work. 

> it seems that the samples are extracted from the whole dataset: both from the train set and the val set. Is that true?

Actually not. `scenario_builder=nuplan_challenge` restricts that the data are extracted from the test set. 

https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/planning/script/config/common/scenario_builder/nuplan_challenge.yaml#L4

**Comment by ynw2021** [comment]
I see, thank you very much
