### ISSUE TITLE
Question about the size of nuplan_cache dataset

### ISSUE THREAD

**Issue by weiaiF** [jchengai/planTF#9]
I noticed that the total data volume used here is 1 million. Is this amount of data a necessary condition for achieving the corresponding performance in the paper? And I noticed that the cached data volume generated by PDM is not as large.  And I'm curious about how much time is needed for training on a dataset of 1 million samples. 
plantf paper `limit_total_scenarios: 1000000 `
pdm papaer `num_scenarios_per_type: 4000 `

**Comment by jchengai** [comment]
Hi, @weiaiF. PDM is essentially a rule-based planner where the learning part is only used for higher open-loop score. Therefore, it is not very sensitive to training samples. 

>  Is this amount of data a necessary condition for achieving the corresponding performance in the paper? 

From my experiments, 300k data already gives good results and scaling to 1M further improves the results. However, using more than 1M does not show clear improvements.

> And I'm curious about how much time is needed for training on a dataset of 1 million samples.

About 20hr on 4 GPUs.

**Comment by weiaiF** [comment]
Thanks! Very useful experimental techniques!

**Comment by weiaiF** [comment]
By the way, how much disk space is required to generate a 1 million-cache file here?

**Comment by jchengai** [comment]
About 380G.
